import { 
  SiReact, SiNextdotjs, SiTypescript, SiTailwindcss, 
  SiNodedotjs, SiMongodb, SiOpenai, SiDocker, 
  SiVercel, SiPython, SiPostgresql, SiFlutter, 
  SiRailway, SiGitlab, SiBun, SiNestjs, 
  SiExpress, SiMysql, SiNetlify,
  SiFramer, SiJavascript, SiHtml5, SiCss,
  SiGooglecloud, SiFirebase, SiSupabase, SiRedux, SiStripe, SiRazorpay
} from "react-icons/si";
import { FaAws, FaGithub, FaStar } from "react-icons/fa";
import { TbBrain, TbCloudCode, TbInfinity, TbRoute, TbDeviceMobile, TbDatabase, TbRocket, TbBolt } from "react-icons/tb";
import { 
  HiOutlineLightningBolt, HiOutlineServer, HiOutlineCog, HiOutlineSparkles, 
  HiOutlineCube, HiOutlineBookOpen, HiOutlineGlobeAlt, HiOutlineHome, 
  HiOutlineScissors, HiOutlineClock 
} from "react-icons/hi";

export const iconMap: Record<string, React.ReactNode> = {
  react: <SiReact />,
  nextjs: <SiNextdotjs />,
  typescript: <SiTypescript />,
  tailwind: <SiTailwindcss />,
  nodejs: <SiNodedotjs />,
  mongodb: <SiMongodb />,
  openai: <SiOpenai />,
  docker: <SiDocker />,
  vercel: <SiVercel />,
  python: <SiPython />,
  postgresql: <SiPostgresql />,
  flutter: <SiFlutter />,
  railway: <SiRailway />,
  gitlab: <SiGitlab />,
  bun: <SiBun />,
  nestjs: <SiNestjs />,
  express: <SiExpress />,
  mysql: <SiMysql />,
  aws: <FaAws />,
  netlify: <SiNetlify />,
  framer: <SiFramer />,
  javascript: <SiJavascript />,
  html: <SiHtml5 />,
  css: <SiCss />,
  brain: <TbBrain />,
  cloud: <TbCloudCode />,
  infinity: <TbInfinity />,
  route: <TbRoute />,
  mobile: <TbDeviceMobile />,
  database: <TbDatabase />,
  rocket: <TbRocket />,
  lightning: <HiOutlineLightningBolt />,
  server: <HiOutlineServer />,
  cog: <HiOutlineCog />,
  sparkles: <HiOutlineSparkles />,
  langchain: <HiOutlineSparkles color="#A3FF12" />, // Fallback for SiLangchain
  firebase: <SiFirebase />,
  supabase: <SiSupabase />,
  redux: <SiRedux />,
  stripe: <SiStripe />,
  razorpay: <SiRazorpay />,
  gcp: <SiGooglecloud />,
  cube: <HiOutlineCube />,
  book: <HiOutlineBookOpen />,
  globe: <HiOutlineGlobeAlt />,
  home: <HiOutlineHome />,
  scissors: <HiOutlineScissors />,
  bolt: <TbBolt />,
  clock: <HiOutlineClock />,
  github: <FaGithub />,
  star: <FaStar />,
};
